package de.contracts.contracts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-10T21:03:41.937+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://contracts.de/contracts", name = "ContractsPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContractsPort {

    @WebMethod
    @WebResult(name = "calculateContractResponse", targetNamespace = "http://contracts.de/contracts", partName = "calculateContractResponse")
    public CalculateContractResponse calculateContract(
        @WebParam(partName = "calculateContractRequest", name = "calculateContractRequest", targetNamespace = "http://contracts.de/contracts")
        CalculateContractRequest calculateContractRequest
    );
}
